---
name: 'Terraform Setup Config'
description: 'Setup Config'

inputs:
  dev_config_file:
    required: true
    description: 'config file'
    type: string
  prd_config_file:
    required: true
    description: 'config file'
    type: string

runs:
  using: 'composite'
  steps:
    - run: mkdir environments
      shell: sh
    # TODO: fix single quote escaping in config files
    - run: echo '${{ inputs.dev_config_file }}' > environments/development.tfvars
      shell: sh
    - run: echo '${{ inputs.prd_config_file }}' > environments/production.tfvars
      shell: sh
