---
name: 'Gradle Build and Docker Release'
description: 'Build and release the artifact and docker image'
inputs:
  name:
    required: true
    description: 'Name of the project which will be used name the docker image'
    type: string
  version:
    required: false
    description: 'Version of the project which will be used tag the docker image'
    type: string
  aws_access_key_id:
    required: true
    description: 'AWS access key ID'
  aws_secret_access_key:
    required: true
    description: 'AWS secret access key'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4.2
    - name: Execute Gradle build
      run: gradle build
      shell: bash
    - name: Releasing project
      uses: go-picky/picky-cicd/actions/docker/build-and-push@main
      with:
        name: ${{ inputs.name }}
        version: ${{ inputs.version }}
        aws_access_key_id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
