---
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: false
        type: string
      job:
        description: 'Job to run'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      CLUSTER_ARN:
        required: true

jobs:
  dev-deploy:
    environment: development
    runs-on: self-hosted
    if: ${{ inputs.job == 'dev-deploy'}}
    steps:
      - uses: actions/checkout@v3
      - uses: go-picky/picky-cicd/actions/aws/deploy@main
        with:
          name: ${{ inputs.name }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_arn: ${{ secrets.CLUSTER_ARN }}

  prod-deploy:
    environment: production
    runs-on: self-hosted
    if: ${{ inputs.job == 'prod-deploy'}}
    steps:
      - uses: actions/checkout@v3
      - uses: go-picky/picky-cicd/actions/aws/deploy@main
        with:
          name: ${{ inputs.name }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_arn: ${{ secrets.CLUSTER_ARN }}