---
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      job:
        description: 'Job to run'
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      destination_path:
        description: 'Path of destination directory to deploy (directory or file)'
        required: false
        type: string
        default: ''
      require_unzip:
        description: 'Unzip artifact'
        required: false
        type: boolean
        default: false
        
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ARTIFACTS_BUCKET_NAME:
        required: true
      AWS_DEV_DEPLOY_BUCKET_NAME:
        required: true
      AWS_PRD_DEPLOY_BUCKET_NAME:
        required: true
      AWS_REGION:
        required: true

jobs:
  dev-deploy:
    environment: development
    runs-on: ubuntu-latest
    if: ${{ inputs.job == 'dev-deploy'}}
    steps:
      - uses: actions/checkout@v3
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://${{ secrets.AWS_ARTIFACTS_BUCKET_NAME}}/${{ inputs.artifact_name }}
          destination: .
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
      - run: echo "SOURCE=${{ inputs.artifact_name }}" >> $GITHUB_ENV
      - run: |
          mkdir upload
          tar -xf ${{ inputs.artifact_name }} -C ./upload
          echo "SOURCE=upload/out/" >> $GITHUB_ENV
        if: ${{ inputs.require_unzip }}
      - run: ls -l
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: sync
          source: ${{ env.SOURCE }}
          destination: s3://${{ secrets.AWS_DEV_DEPLOY_BUCKET_NAME}}/${{ inputs.destination_path }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          flags: --acl public-read
  prod-deploy:
    environment: production
    runs-on: ubuntu-latest
    if: ${{ inputs.job == 'prod-deploy'}}
    steps:
      - uses: actions/checkout@v3
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://${{ secrets.AWS_ARTIFACTS_BUCKET_NAME}}/${{ inputs.artifact_name }}
          destination: .
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ${{ inputs.artifact_name }}
          destination: s3://${{ secrets.AWS_PRD_DEPLOY_BUCKET_NAME}}/${{ inputs.destination_path }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          flags: --acl public-read
