---
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: false
        type: string
      job:
        description: 'Job to run'
        required: true
        type: string
      # basepath:
      #   description: 'directory of application to be deployed'
      #   required: true
      #   type: string
      matrix:
        description: 'matrix of applications to deploy'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      DEV_CLUSTER_ARN:
        required: true
      PRD_CLUSTER_ARN:
        required: true

jobs:
  dev-deploy:
    runs-on: self-hosted
    strategy:
      matrix: ${{ fromJson(inputs.matrix) }}
    if: ${{ inputs.job == 'dev-deploy'}}
    steps:
      - uses: actions/checkout@v3
      - uses: go-picky/picky-cicd/actions/aws/deploy@main
        with:
          basepath: ${{ matrix.app }}
          name: ${{ inputs.name }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_arn: ${{ secrets.CLUSTER_ARN }}
          environment: development

  prod-deploy:
    runs-on: self-hosted
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    if: ${{ inputs.job == 'prod-deploy'}}
    steps:
      - uses: actions/checkout@v3
      - uses: go-picky/picky-cicd/actions/aws/deploy@main
        with:
          basepath: ${{ inputs.basepath }}
          name: ${{ inputs.name }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_arn: ${{ secrets.CLUSTER_ARN }}
          environment: production
