---
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: false
        type: string

jobs:
  Validate:
    runs-on: ubuntu-latest
    container:
      image: gradle:7.4.2-jdk8
    steps:
      - uses: actions/checkout@v3
      - uses: go-picky/picky-cicd/actions/gradle/validate@main
  Release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: Validate
    runs-on: ubuntu-latest
    container:
      image: gradle:7.4.2-jdk8
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git config --global --add safe.directory /__w/${{ inputs.name }}/${{ inputs.name }}
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: gradle -PnewVersion=$RELEASE_VERSION setVersion
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add build.gradle.kts
          git commit -m "Update project version to ${RELEASE_VERSION}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Uploading build artifact
        run: gradle publish
